run pep8 separately for each Python file
This makes it easier to see which file(s) have problems, and it
mirrors what is done for rstcheck.

Signed-off-by: Richard Hansen <rhansen@rhansen.org>

diff --git a/t/run-tests b/t/run-tests
--- a/t/run-tests
+++ b/t/run-tests
@@ -52,12 +52,16 @@ rstcheck_file doc/gitolite.rst
 # E123: closing bracket does not match indentation of opening bracket's line
 # => not raised on all pep8 version, and really constraining. We can
 # probably keep ignoring it forever.
-if ! pep8 "$d"/../git-multimail/git_multimail.py "$d"/test-env --ignore=W503,E402,E501,E123
-then
-    record_error PEP8
-else
-    echo "No new PEP8 error found: PASS"
-fi
+pep8_file () {
+    if ! pep8 "$d"/../"$1" --ignore=W503,E402,E501,E123
+    then
+	record_error PEP8
+    else
+	echo "No new PEP8 error in $1 found: PASS"
+    fi
+}
+pep8_file git-multimail/git_multimail.py
+pep8_file t/test-env
 
 if ! "$d/test-email-content"
 then
