write error messages to stderr
Signed-off-by: Richard Hansen <rhansen@rhansen.org>

diff --git a/t/run-tests b/t/run-tests
--- a/t/run-tests
+++ b/t/run-tests
@@ -67,7 +67,7 @@ fi
 
 if [ -n "$errors" ]
 then
-    echo "Errors found in:$errors"
+    echo "Errors found in:$errors" >&2
 fi
 
 exit $retcode
